# Generated by Django 5.2.12 on 2026-04-11 10:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FounderVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='İsteğe bağlı başlık (oynatıcının üstünde).', max_length=255)),
                ('video', cloudinary.models.CloudinaryField(blank=True, help_text='Cloudinary’e yüklenen video (tercihen MP4 / tarayıcı uyumlu).', max_length=255, null=True, verbose_name='video')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Founder video',
                'verbose_name_plural': 'Founder videos',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
