# Generated by Django 5.2.13 on 2026-04-18 13:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_founder_video_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='İsteğe bağlı video (Cloudinary).', max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='İsteğe bağlı kapak görseli (Cloudinary).', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Cloudinary’e yüklenen görsel.', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Cloudinary’e yüklenen MP4 (H.264 önerilir).', max_length=255, null=True, verbose_name='video'),
        ),
    ]
