# Generated by Django 5.2.13 on 2026-05-17 08:38

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_foundervideo_poster_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='website.project')),
            ],
            options={
                'verbose_name': 'Project update',
                'verbose_name_plural': 'Project updates',
                'ordering': ['-published_at', 'sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdateMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Cloudinary’e yüklenen görsel (video ile birlikte kullanmayın).', max_length=255, null=True, verbose_name='image')),
                ('video', cloudinary.models.CloudinaryField(blank=True, help_text='Cloudinary’e yüklenen video (görsel ile birlikte kullanmayın).', max_length=255, null=True, verbose_name='video')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='website.projectupdate')),
            ],
            options={
                'verbose_name': 'Project update media',
                'verbose_name_plural': 'Project update media',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
