# Generated by Django 5.2.13 on 2026-05-17 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_project_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectupdate',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
