# Generated by Django 5.2.13 on 2026-05-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_projectupdate_published_at_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdatemedia',
            name='poster_ref',
            field=models.CharField(blank=True, help_text='Video önizleme görseli: Cloudinary public_id veya URL. Boş bırakırsanız varsayılan önizleme kullanılır (dgppgkttceva7syh0t4h).', max_length=512),
        ),
    ]
